version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: ufrr-postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: sgcursos
    volumes:
      - ./prisma/postgres-data:/var/lib/postgresql/data
      - ./prisma/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  prisma-api:
    container_name: ufrr-prisma-api
    stdin_open: true
    hostname: prisma
    build:
      context: ./prisma
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "5050:5050"
      - "5555:5555"
    restart: always

  ganache:
    image: ufrr-ganache
    container_name: ufrr-ganache
    build:
      context: ./ethereum
      dockerfile: GanacheDockerfile
    ports:
      - '8545:8545'
    networks:
      - eth-network

  ethereum-api:
    image: ufrr-ethereum-api
    container_name: ufrr-ethereum
    build:
      context: ./ethereum
      dockerfile: APIDockerfile
    depends_on:
      - ganache
    ports:
      - '4041:4041'
    networks:
      - eth-network
    
  nextjs:
    container_name: ufrr-nextjs
    build:
      context: ./frontend
    ports:
      - "3000:3000"


networks:
  eth-network:

volumes:
  postgres-data: