version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: sgcursos
    volumes:
      - ./prisma/postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  prisma-api:
    stdin_open: true
    build:
      context: ./prisma
      dockerfile: Dockerfile
    container_name: prisma-postgres-api
    depends_on:
      - postgres
    ports:
      - "5050:5050"
      - "5555:5555"
    restart: always

  ganache:
    build:
      context: ./ethereum
      dockerfile: GanacheDockerfile
    container_name: ganache
    ports:
      - '8545:8545'
    networks:
      - eth-network

  ethereum-api:
    build:
      context: ./ethereum
      dockerfile: APIDockerfile
    container_name: eth-api
    depends_on:
      - ganache
    ports:
      - '4041:4041'
    networks:
      - eth-network
    
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"


networks:
  eth-network:

volumes:
  postgres-data: