version: "3.9"
services:
    app:
        build: .
        ports:
            - "3000:3000"
        depends_on:
            - db
        environment:
            DATABASE_URL: ${DATABASE_URL}
    db:
        image: postgres:14
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 1234
            POSTGRES_DB: sgcursos
        volumes:
            - db-data:/var/lib/postgresql/data
volumes:
    db-data:
