FROM node:14


WORKDIR /app

COPY . .

COPY package*.json ./
COPY prisma ./prisma/

# RUN apt-get update -y && apt-get upgrade -y

RUN npm install

CMD [ "sh", "-c", "npx prisma migrate dev --name init && node dist/index.js" ]
