version: "3.9"
services:
    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - backend_network

        # node_server:
        #     build:
        #         context: .
        #         dockerfile: Dockerfile
        #     ports:
        #         - "3000:3000"
        #     depends_on:
        #         - postgres
        #     env_file:
        #         - .env

networks:
    backend_network:
        driver: bridge

volumes:
    postgres_data:
